spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.100:9411/
  rabbitmq:
    host: 192.168.99.100
    port: 5672
  cloud:
    bus:
      enabled: true
      destination: configXchangebus
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${discountms.eureka.url:http://192.168.99.100:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  pattern:
    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"