spring:
  cloud:
    config:
      server:
        git:
          #uri: C:\work\ksr\banglore2020labsconfig
          uri: https://github.com/prabhakarmishra/MSVirtualSession.git
          searchPaths: ConfigData
          skipSslValidation: true
    bus:
      enabled: true
      destination: configXchangebus
  rabbitmq:
    host: rabbitmq-master
    port: 5672

server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: '*'